version: 0.2

phases:
  install:
    commands:
      # Install Yarn.
      - apt-get update -y
      - apt-get install apt-transport-https
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update -y
      - apt-get install -y yarn
  pre_build:
    commands:
      # Install dependancy packages.
      - yarn install
  build:
    commands:
      # Package artifacts.
      - yarn lint
      - yarn package --s3-bucket $BUCKET_NAME
artifacts:
  type: zip
  files:
    - sam.packaged.yml
